# Generated by Django 3.2.9 on 2022-02-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_photo',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='сhairman',
            name='chairman_photo',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
